version: '3.1'

services:

  postgres:
    image: postgres
    tmpfs: /var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: liveview_todo
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
